services:
  app:
    build: .
    image: aia1010/lab8-app:latest
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://db:27017/lab8
    depends_on:
      - db

  db:
    image: mongo:6
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: